name: alamuti
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_storage: ^2.0.3
  image_picker: ^0.8.4+4
  flutter_image_compress: ^1.1.0
  signalr_core: ^1.1.1
  bubble: ^1.2.1
  chips_choice_null_safety: ^2.0.4
  infinite_scroll_pagination: ^3.1.0
  url_launcher: ^6.0.17
  flutter_image_slideshow: ^0.1.2
  connectivity: ^3.0.6
  shared_preferences: ^2.0.11
  get: ^4.6.1
  dio: ^4.0.4

  flutter_countdown_timer: ^4.1.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/logo.png
    - assets/logo/no-image.png
    - assets/icons/sheep.png
    - assets/3.0x/confused-face.png
    - assets/3.0x/empty-box.png
    - assets/3.0x/frustrated-face.png
   
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: IRANSansX
      fonts:
        - asset: assets/fonts/IRANSansX-Thin.ttf
          weight: 100
        - asset: assets/fonts/IRANSansX-UltraLight.ttf
          weight: 200
        - asset: assets/fonts/IRANSansX-Light.ttf
          weight: 300
        - asset: assets/fonts/IRANSansX-Regular.ttf
          weight: 400
        - asset: assets/fonts/IRANSansX-Medium.ttf
          weight: 500
        - asset: assets/fonts/IRANSansX-Demibold.ttf
          weight: 600
        - asset: assets/fonts/IRANSansX-Bold.ttf
          weight: 700
        - asset: assets/fonts/IRANSansX-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/IRANSansX-Black.ttf
          weight: 900
    - family: IRANSansXFaNum
      fonts:
        - asset: assets/fonts/IRANSansXFaNum-Thin.ttf
          weight: 100
        - asset: assets/fonts/IRANSansXFaNum-UltraLight.ttf
          weight: 200
        - asset: assets/fonts/IRANSansXFaNum-Light.ttf
          weight: 300
        - asset: assets/fonts/IRANSansXFaNum-Regular.ttf
          weight: 400
        - asset: assets/fonts/IRANSansXFaNum-Medium.ttf
          weight: 500
        - asset: assets/fonts/IRANSansXFaNum-Demibold.ttf
          weight: 600
        - asset: assets/fonts/IRANSansXFaNum-Bold.ttf
          weight: 700
        - asset: assets/fonts/IRANSansXFaNum-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/IRANSansXFaNum-Black.ttf
          weight: 900
    
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
